volumes:
  postgres-data: {}

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/:z